### ISSUE TITLE
Maybe tag a release?

### ISSUE THREAD

**Issue by darix** [emersion/libliftoff#40]
or is anything blocking it? it would help people who want to package it for distros e.g. to package https://github.com/Plagman/gamescope

**Comment by emersion** [comment]
I don't think this project is ready for an initial release yet. I'll try my best to reduce ABI breakage, but I can't guarantee I won't make breaking changes. For now I'd prefer downstream to link statically if possible.

**Comment by darix** [comment]
> I don't think this project is ready for an initial release yet. I'll
> try my best to reduce ABI breakage, but I can't guarantee I won't
> make breaking changes. For now I'd prefer downstream to link
> statically if possible.

1. Every dev using your library will have to deal with the API/ABI breakages anyway. whether you do releases or not. so from that standpoint you don't gain anything from not doing releases.
2. [semantic versioning][1] actually gives us tools to express those incompatibilities in the version number and shared library version.
3. There are tools that help you to identify when you break the API/ABI. [abimap][2]

With those tools at hand it should be easy to provide releases with proper versioning.


[1]: https://semver.org/
[2]: https://pypi.org/project/abimap/

-- 
          openSUSE - SUSE Linux is my linux
              openSUSE is good for you
                  www.opensuse.org

**Comment by darix** [comment]
https://devconfcz2020a.sched.com/event/YOqh/dont-break-your-users-keep-your-apiabi-stable

A talk about the tooling.

**Comment by ddevault** [comment]
I assure you, @emersion is quite the competent release manager. He understands how the process works.

**Comment by darix** [comment]
Well even better. So lets do a release :D

**Comment by stephanlachnit** [comment]
I'm strongly in favor of this as well.

> I don't think this project is ready for an initial release yet. I'll try my best to reduce ABI breakage, but I can't guarantee I won't make breaking changes. For now I'd prefer downstream to link statically if possible.

At least for Debian this is not really an option. Even if the soversion changes daily, this is still better than statically linking.

Are there any news regarding a release? I'm planning to package gamescope anyway, and will probably just release git snapshots of this library to Debian, if there is no release planned.

**Comment by emersion** [comment]
There are a few breaking API changes I'd like to do before an initial release (see opened PRs). After these are merged, I think I'd be comfortable shipping an initial release, without any guarantee wrt. future API/ABI stability.

**Comment by stephanlachnit** [comment]
Cool, thanks for the update!

**Comment by emersion** [comment]
0.1.0 is released: https://github.com/emersion/libliftoff/releases/tag/v0.1.0

**Comment by darix** [comment]
Thank you!
