### ISSUE TITLE
Consider renaming liftoff_output to liftoff_crtc

### ISSUE THREAD

**Issue by emersion** [emersion/libliftoff#57]
A `liftoff_output` is really just a KMS CRTC. The name "output" was chosen because the term "CRTC" is only historical, KMS CRTCs have nothing to do with actual Cathode Ray Tube Controllers.

Is the name "output" confusing to users? Would it be better to use the term "CRTC" for consistency with the KMS API?

**Comment by fooishbar** [comment]
Weston uses `output` for CRTC and `head` for connector. I don't like the names at all but didn't think of anything better either.

**Comment by subdiff** [comment]
Personally when working on libliftoff I didn't found the liftoff_output name to be confusing. Actually I think from the perspective of a newcomer "CRTC" is more difficult to understand.

In KWinFT the "Output" class is a composition of a CRTC and an active connector, represent a fully functional display pipeline, so to say. As @fooishbar notes the interpretation in Weston seems to be a bit different. It would be nice to come to a shared understanding of what "output" means, but regarding this ticket both maps fine to liftoff_output as iirc the connector is irrelevant to liftoff's API.

**Comment by emersion** [comment]
Thanks for the feedback! Glad to hear that using something else than CRTC isn't too confusing. :)

I guess some wording I've seen elsewhere is "pipe/sink" (i915?). Probably a little better than output/head, but oh well.

**Comment by emersion** [comment]
All right, closing this since it seems to be a non-issue.
